### ISSUE TITLE
How to include/reference complex data structures/objects?

### ISSUE THREAD

**Issue by ex-nerd** [zerwes/hiyapyco#13]
This is a great tool but it seems to lack (at least documentation about) a way to include/interpolate nested structures, e.g. I have some default values (in my case, AWS Cloudformation Tag definitions) that I need insert a bunch of times at different nesting levels.  A more simple example might look something like this:

`defaultprefs.yaml`

``` yaml
pref1: 1
pref2: 2
```

`stream.yaml`

``` yaml
user1:
    prefs: {% include 'defaultprefs.yaml' %}
user2:
    prefs: {% include 'defaultprefs.yaml' %}

---
user1:
    prefs:
        pref2: override2
user2:
    prefs:
        pref3: 3
```

With a deep-merge output of:

``` yaml
user1:
    prefs:
        pref1: 1
        pref2: override2
user2:
    prefs:
        pref1: 1
        pref2: 2
        pref3: 3
```

Obviously, the order that hiyapyco interpolates the jinja2 doesn't let this work (I'd have to wrap the `{` character in quotes to at least make the yaml parseable) but it gives an idea of the functionality. A more realistic solution would be similar to the `!include` call described [here](http://stackoverflow.com/questions/528281/how-can-i-include-an-yaml-file-inside-another).

I assume it's possible to override/extend the `ODYLDo` but it would be nice if it could do this on its own.

**Comment by ex-nerd** [comment]
I've been playing around with some include code (I can submit a PR if you'd like to see what I have so far) but it looks like I'm bumping into #7 before I can both include (default values) and merge (new values in-line):

```yaml
one: &ONE !include inc.yaml
two:
  <<: *ONE
  three: 3
```
