### ISSUE TITLE
Merging arrays of dicts?

### ISSUE THREAD

**Issue by phybros** [zerwes/hiyapyco#25]
Hi, I had some yaml files with an array of dicts in it, and I'm confused how hiyapyco is supposed to behave in this scenario. Not sure if it's a bug or not.

base.yml

```yaml
key_one: 1
key_two: 2
array_of_dicts:
- dict_key_one: a
  dict_key_two: b
  dict_key_three: c
- dict_key_one: a1
  dict_key_two: b1
  dict_key_three: c1
```

layer.yml

```yaml
key_two: 2222
array_of_dicts:
- dict_key_one: a2
  dict_key_two: b2
  dict_key_three: c2
```

merge.py

```py
import hiyapyco

CONF = hiyapyco.load("base.yml", "layer.yml", method=hiyapyco.METHOD_MERGE)
print hiyapyco.dump(CONF)
```

result:

```yaml
key_one: 1
key_two: 2222
array_of_dicts:
- {dict_key_one: a2, dict_key_two: b2, dict_key_three: c2}
- {dict_key_one: a1, dict_key_two: b1, dict_key_three: c1}
```

I thought it would have produced:

```yaml
key_one: 1
key_two: 2222
array_of_dicts:
- {dict_key_one: a, dict_key_two: b, dict_key_three: c}
- {dict_key_one: a1, dict_key_two: b1, dict_key_three: c1}
- {dict_key_one: a2, dict_key_two: b2, dict_key_three: c2}
```

Is this a bug?
