### ISSUE TITLE
is there a way to use ruamel YAML isntead of pyyaml?

### ISSUE THREAD

**Issue by ghost** [zerwes/hiyapyco#39]
when loading files that have aliases and anchors, because of PyYaml the aliases get renamed to ie id001

```
conf = hiyapyco.load('/tmp/yaml1.yaml', '/tmp/yaml2.yaml','/tmp/yaml3.yml','/tmp/yaml4.yml', '/tmp/yaml5.y
     ...: ml','/tmp/yaml6.yml', method=hiyapyco.METHOD_MERGE, interpolate=True, failonmissingfiles=True)     
```

here's the yaml6 file - the one with the anchors/aliases

```
cat yaml6.yml 
definitions: 
  steps:
    - step: &build-test
        name: Build and test
        script:
          - mvn package
        artifacts:
          - target/**

pipelines:
  branches:
    develop:
      - step: *build-test
    master:
      - step: *build-test
```

here's a partial of the output

```
  nr2: 6
key:
- value line 1
- value line 2
- value line 3
definitions:
  steps:
  - step: &id001
      name: Build and test
      script:
      - mvn package
      artifacts:
      - target/**
pipelines:
  branches:
    develop:
    - step: *id001
    master:
    - step: *id001
```

ruamel yamle has addressed and fixed this issue already, is there  a overwrite for this? I don't see a flag of sorts in the __ini__.py
