### ISSUE TITLE
Weird merge behavior with anchors

### ISSUE THREAD

**Issue by sylvaindd** [zerwes/hiyapyco#69]
Hi,

I am facing a weird behavior when merging while using anchors.
Without anchors, this isn't happening, but I can't understand why this is happening and how to fix it.

```python
hiyapyco.load('''
app-specs: &app-specs
  resources:
    requests:
      memory: "1"
      cpu: "1"

applications:
  app1:
    <<: *app-specs
    imageTag: azerty
  app2:
    <<: *app-specs
    imageTag: azerty
    replicas: 1
''', 
'''
applications:
  app1:
    imageTag: azerty
    replicas: 1
    resources:
      requests:
        memory: "2"
        cpu: "2"
  app2:
    imageTag: azerty
    replicas: 1
''', method=hiyapyco.METHOD_MERGE, mergelists=True, interpolate=True, failonmissingfiles=True)
```

Here is the merged dict, I expected to only have app1 with overrided resources, but both are :
```json
{
  "app-specs": {
    "resources": {
      "requests": {
        "memory": "2",
        "cpu": "2"
      }
    }
  },
  "applications": {
    "app1": {
      "resources": {
        "requests": {
          "memory": "2",
          "cpu": "2"
        }
      },
      "imageTag": "azerty",
      "replicas": 1
    },
    "app2": {
      "resources": {
        "requests": {
          "memory": "2",
          "cpu": "2"
        }
      },
      "imageTag": "azerty",
      "replicas": 1
    }
  }
}
```
Here is the yaml dump :
```yaml
app-specs:
  resources: &id001
    requests:
      memory: '2'
      cpu: '2'
applications:
  app1:
    resources: *id001
    imageTag: azerty
    replicas: 1
  app2:
    resources: *id001
    imageTag: azerty
    replicas: 1
```
